I had previously commented out the timestr() function from helpers and put it in gv.py since I needed to use it there to set up values to be logged and it didn't seem to be called from anywhere else in the sip program but I later discovered that at least the email_adj.py plugin imports that timestr function from helpers.  I then tried to uncomment the function in helpers.py and import it to use it in gv.py but this cased a circular import issue like this:
Traceback (most recent call last):
  File "sip.py", line 17, in <module>
    import gv
  File "/home/pi/SIP/gv.py", line 101, in <module>
    logged_values.append([ _('duration'), duration_str() ])
  File "/home/pi/SIP/gv.py", line 98, in duration_str
    from helpers import timestr
  File "/home/pi/SIP/helpers.py", line 27, in <module>
    from gpio_pins import GPIO, pin_rain_sense, pin_relay
  File "/home/pi/SIP/gpio_pins.py", line 23, in <module>
    if gv.use_pigpio:
AttributeError: 'module' object has no attribute 'use_pigpio'

So, for now, I've duplicated the timestr() function in gv.py so not an identical function is defined in
both helpers.py and gv.py.  Hopefully we can figure to way to fix this and import it into gv.py instead.